version: "3.7"
services:
  api-rest-proyectos-micro:
    container_name: api-rest-proyectos-micro
    image: api-rest-proyectos-micro:v1
    build:
      context: .
    ports:
      - "3002"
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=3002
    networks:
      - api-rest-proyectos-micro

  balanceador-carga:
    container_name: balanceador-carga
    image: balanceador-carga:v1
    build: ./balanceador
    ports:
      - "3004:80"
    networks:
      - api-rest-proyectos-micro
networks:
  api-rest-proyectos-micro:
