version: "3.7"
services:
  api-rest-proyectos-micro:
    container_name: api-rest-proyectos-micro
    image: api-rest-proyectos-micro:v1
    build:
      context: .
    ports:
      - "3002"
    networks:
      - api-rest-proyectos-micro
  api-rest-proyectos-micro-2:
    container_name: api-rest-proyectos-micro-2
    image: api-rest-proyectos-micro:v1
    ports:
      - "3002"
    networks:
      - api-rest-proyectos-micro
  balanceador-carga:
    container_name: balanceador-carga
    image: balanceador-carga:v1
    build: ./balanceador
    ports:
      - "3004:80"
    networks:
      - api-rest-proyectos-micro
networks:
  api-rest-proyectos-micro:
